export enum IgdbGameCategoryEnum {
 MainGame = 0,
 DlcAddon = 1,
 Expansion = 2,
 Bundle = 3,
 StandaloneExpansion = 4,
 Mod = 5,
 Episode = 6,
 Season = 7,
 Remake = 8,
 Remaster = 9,
 ExpandedGame = 10,
 Port = 11,
 Fork = 12,
 Pack = 13,
 Update = 14,
}

export const IGDB_GAME_CATEGORY_TRANSLATION_KEYS: Record<number, string> = {
 [IgdbGameCategoryEnum.MainGame]: 'main_game',
 [IgdbGameCategoryEnum.DlcAddon]: 'dlc_addon',
 [IgdbGameCategoryEnum.Expansion]: 'expansion',
 [IgdbGameCategoryEnum.Bundle]: 'bundle',
 [IgdbGameCategoryEnum.StandaloneExpansion]: 'standalone_expansion',
 [IgdbGameCategoryEnum.Mod]: 'mod',
 [IgdbGameCategoryEnum.Episode]: 'episode',
 [IgdbGameCategoryEnum.Season]: 'season',
 [IgdbGameCategoryEnum.Remake]: 'remake',
 [IgdbGameCategoryEnum.Remaster]: 'remaster',
 [IgdbGameCategoryEnum.ExpandedGame]: 'expanded_game',
 [IgdbGameCategoryEnum.Port]: 'port',
 [IgdbGameCategoryEnum.Fork]: 'fork',
 [IgdbGameCategoryEnum.Pack]: 'pack',
 [IgdbGameCategoryEnum.Update]: 'update',
};
